#! /bin/sh

MODEL_TFLITE=$1
MODEL_TFLITE_MICRO=$2
REPLACE_TEXT=$3
MODEL_NAME=$4

xxd -i "$MODEL_TFLITE" > "$MODEL_TFLITE_MICRO"
echo $REPLACE_TEXT

sed -i 's/'"$REPLACE_TEXT"'/'"$MODEL_NAME"'/g' "$MODEL_TFLITE_MICRO"
#cat "$MODEL_TFLITE_MICRO"
